name: chat_sample
description: Chat Sample

version: 0.2.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectycube_sdk: ^1.1.3
  shared_preferences: ^0.5.8
  image_picker: ^0.6.7+4
  fluttertoast: ^3.1.3
  cached_network_image: 2.0.0-rc.1
  photo_view: ^0.5.0
  device_id: ^0.2.0
  firebase_core: ^0.7.0
  firebase_messaging: 8.0.0-dev.14
  flutter_local_notifications: ^4.0.0
  connectivity: ^2.0.2
  logging: ^0.11.4
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  random_string: ^2.1.0

  carousel_pro: ^1.0.0

  webview_flutter: ^1.0.7
  flutter_webview_plugin: ^0.3.11
  share: ^0.6.5+4
  wc_flutter_share: ^0.2.2

  google_sign_in: ^4.4.4

  cupertino_icons: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/splash.png
    - assets/service.json
    - assets/Logo.PNG
    - assets/Slide1.PNG
    - assets/Slide2.PNG
    - assets/google_logo.png
    - assets/TOS.txt